### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by nicokuyum** [jetbridge/flask_cognito#10]
Hello,
Thanks for the repo, it is indeed very useful!

Have you considered adding a license such as MIT?

It would allow the usage of the library in projects which need consent from the owners to use them.

**Comment by revmischa** [comment]
Yeah MIT is fine. Want to send a PR?

**Comment by nicokuyum** [comment]
@revmischa Created https://github.com/jetbridge/flask_cognito/pull/11
