### ISSUE TITLE
Failed Authentication is overly verbose

### ISSUE THREAD

**Issue by cybojenix** [jetbridge/flask_cognito#13]
Failed authentication attempts get logged at the Error level, with no way to configure it outside of disabling logging for the entire package.

Please provide a way to configure the Log Level for Auth issues, or set to Info level by default.

The rationale for this would be that an API Provider would not need to action a user entering their credentials incorrectly.

---

Lines affected:
- https://github.com/jetbridge/flask_cognito/blob/master/flask_cognito.py#L114
- https://github.com/jetbridge/flask_cognito/blob/master/flask_cognito.py#L191

To retain the exception details in the error, you can include it via `exc_info`:
```py
log.info("Authentication Failed", exc_info=e)
log.info("Authentication Failed", exc_info=True)
```

**Comment by revmischa** [comment]
Sounds like a good idea! PR's very welcome
