### ISSUE TITLE
Broken Pypi link

### ISSUE THREAD

**Issue by Sytten** [jetbridge/flask_cognito#2]
Just to let you know, the homepage link on Pypi is broken. It points to: `https://github.com/jetbridge/flask-cognito`. Maybe you should also put a banner in the readme to point to Pypi?
Keep up the good work, cheers!

**Comment by revmischa** [comment]
Thanks! just uploaded a fix

**Comment by Sytten** [comment]
Maybe also change the URL in the `setup.py`?

**Comment by revmischa** [comment]
Just pushed the changes

**Comment by Sytten** [comment]
Thanks!
